# Generated by Django 5.1.4 on 2025-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ratings_created_at_ratings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='comment',
            field=models.CharField(max_length=400),
        ),
    ]
