# Generated by Django 5.1.4 on 2025-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(default='pending', max_length=45),
        ),
    ]
