# Generated by Django 5.1.4 on 2025-01-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_posts_updated_at_requests_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusservices',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='statusservices',
            name='status',
            field=models.CharField(default='en proceso', max_length=45),
        ),
    ]
