# Generated by Django 5.1.4 on 2025-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_savedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
