# Generated by Django 5.1.4 on 2025-01-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_posts_issaved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='isSaved',
        ),
    ]
