# Generated by Django 5.1.4 on 2025-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_remove_posts_issaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='posts',
            name='disponibility',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='requests',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='statusservices',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
